@startuml

actor USER as "Reporting User"

rectangle WorldDB

rectangle "World Population System" {

    usecase UC1 as "Runs any of the 32 Reports available on the App"

    usecase UCa as "Prints out any of the 32 reports based on user choice"

    USER - UC1
    UC1 ..> UCa : include
    UC1 - WorldDB
}

@enduml