name: Workflow for SET09803-G4
on: push

jobs:
  build:
    name: SET09803-G4 action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Unit Tests
        run: mvn -Dtest=com.napier.devops.AppTest test
      - name: Run docker compose with a simulated input # this is so the action does not stay waiting for a user input. the 0 exits the application. also using "docker compose run app" instead of "docker compose up" so that it accepts the "0"
        run: |
          mvn package -DskipTests
          echo "0" | docker compose run app --abort-on-container-exit
